### ISSUE TITLE
BUG: JHHUI-61 - Edit `GroceryItem` fails

### ISSUE THREAD

**Issue by wijohnst** [wijohnst/johnston_home_hub#61]
When editing a `GroceryItem` we make a request to `PATCH: shoppingList/item`. The request throws the following error on the server:

```
CastError: Cast to ObjectId failed for value "{ aisle: 'Beverages' }" (type Object) at path "aisle" because of "BSONTypeError"
    at model.Query.exec (/Users/ISG2330/workspace/personal/johnston_home_hub_backend/node_modules/mongoose/lib/query.js:4780:21)
    at model.Query.Query.then (/Users/ISG2330/workspace/personal/johnston_home_hub_backend/node_modules/mongoose/lib/query.js:4879:15)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  messageFormat: undefined,
  stringValue: `"{ aisle: 'Beverages' }"`,
  kind: 'ObjectId',
  value: { aisle: 'Beverages' },
  path: 'aisle',
  reason: BSONTypeError: Argument passed in must be a string of 12 bytes or a string of 24 hex characters or an integer
      at new BSONTypeError (/Users/ISG2330/workspace/personal/johnston_home_hub_backend/node_modules/bson/lib/error.js:41:28)
      at new ObjectId (/Users/ISG2330/workspace/personal/johnston_home_hub_backend/node_modules/bson/lib/objectid.js:67:23)
      at castObjectId (/Users/ISG2330/workspace/personal/johnston_home_hub_backend/node_modules/mongoose/lib/cast/objectid.js:25:12)
      at ObjectId.cast (/Users/ISG2330/workspace/personal/johnston_home_hub_backend/node_modules/mongoose/lib/schema/objectid.js:246:12)
      at ObjectId.SchemaType.applySetters (/Users/ISG2330/workspace/personal/johnston_home_hub_backend/node_modules/mongoose/lib/schematype.js:1188:12)
      at ObjectId.SchemaType._castForQuery (/Users/ISG2330/workspace/personal/johnston_home_hub_backend/node_modules/mongoose/lib/schematype.js:1622:15)
      at ObjectId.SchemaType.castForQuery (/Users/ISG2330/workspace/personal/johnston_home_hub_backend/node_modules/mongoose/lib/schematype.js:1612:15)
      at ObjectId.SchemaType.castForQueryWrapper (/Users/ISG2330/workspace/personal/johnston_home_hub_backend/node_modules/mongoose/lib/schematype.js:1589:20)
      at castUpdateVal (/Users/ISG2330/workspace/personal/johnston_home_hub_backend/node_modules/mongoose/lib/helpers/query/castUpdate.js:544:19)
      at walkUpdatePath (/Users/ISG2330/workspace/personal/johnston_home_hub_backend/node_modules/mongoose/lib/helpers/query/castUpdate.js:274:22),
  valueType: 'Object'
}
```

**Comment by wijohnst** [comment]
Fix was actually on backend. Closing.
